### ISSUE TITLE
Remove duplicated code

### ISSUE THREAD

**Issue by 3for** [0xPolygonHermez/zkevm-proverjs#108]
In [https://github.com/0xPolygonHermez/zkevm-proverjs/blob/main/src/sm/sm_main/sm_main_exec.js#L410](https://github.com/0xPolygonHermez/zkevm-proverjs/blob/main/src/sm/sm_main/sm_main_exec.js#L410), should remove the duplicated code `|| l.JMP || l.JMPC`：
```
if (l.mOp || l.JMP || l.JMPN || l.JMPC ||  l.hashP || l.hashPLen || l.hashPDigest ||  l.hashK || l.hashKLen || l.hashKDigest /*|| l.JMP || l.JMPC*/) {
```

**Comment by zkronos73** [comment]
Thanks, in current main and develop branches this line was updated.
