### ISSUE TITLE
Run `npm run g16setup` failed

### ISSUE THREAD

**Issue by 3for** [0xPolygonHermez/zkevm-proverjs#115]
When run `npm run g16setup`, get failure info:
```
[DEBUG] snarkJS: processing constraints: 4840000/5127361
[DEBUG] snarkJS: processing constraints: 4850000/5127361
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```
I've changed the `--max-old-space-size=` value, but got the same failure.
How to fix this?

**Comment by 3for** [comment]
Fixed by setting `vm.max_map_count=262144` in `/etc/sysctl.conf`.

**Comment by cwbhhjl** [comment]
请问你前面的 step 都可以执行吗，我在 buildconstanttree 时报了 `WebAssembly.Memory(): could not allocate memory` ，但是内存占用才20%

**Comment by 3for** [comment]
@cwbhhjl Use [https://github.com/0xPolygonHermez/zkevm-prover/tree/main/tools/starkpil/bctree](https://github.com/0xPolygonHermez/zkevm-prover/tree/main/tools/starkpil/bctree) instead.

**Comment by cwbhhjl** [comment]
感谢 我下午通过把 nodejs 从 16 升级到 18 解决了这个问题，这好像是 node 16.x 依赖的 v8 的一个 bug

----------
If `WebAssembly.Memory(): could not allocate memory` appears during the `buildconstanttree` stage, you can check the version of nodejs. If it is v16 or lower, please upgrade to nodejs18. 
If you run node after the upgrade and it prompts that the required version of GLIBC cannot be found, you can run it through the docker image of node18

--------

**Comment by cwbhhjl** [comment]
@3for 另外大佬，我看了你的博客，感觉你对 zkevm 研究很久了，请问你有没有在本地运行起来过一个私链的真实 prover，我刚刚接触这个，发现官方文档local环境起来的prover是个 mock 版，然后打开非mock的选项后又提示一堆依赖找不到，官方也没有相关的说明，有空能不能写个教程介绍下😭
