### ISSUE TITLE
`npm run prove` costs RAM more than 1T 

### ISSUE THREAD

**Issue by eigmax** [0xPolygonHermez/zkevm-proverjs#187]
I found `npm run prove` costs RAM more than 1T, and leads to OOM finally.   I am trying to optimize memory usage by:

```
NODE="--trace-gc --trace-gc-ignore-scavenger --max_semi_space_size=1024 --max-semi-space-size=1024 --max_old_space_size=1024288 --optimize_for_size"
```

But seems not so promising. 

@zkronos73 @krlosMata  any comments on this?  Big thanks!

**Comment by UrsaMajor-t** [comment]
Hi, I see you hava closed this question. Do you know where the problem lies? Is there any good solution?
