### ISSUE TITLE
Is the fflonk powersOfTau28_hez_final  trusted?

### ISSUE THREAD

**Issue by Federico2014** [0xPolygonHermez/zkevm-proverjs#190]
I want to know where the `build/powersOfTau28_hez_final.ptau`  file comes from, is it trusted?

https://github.com/0xPolygonHermez/zkevm-proverjs/blob/71632a87b3f2b942c8a240b120ecb58b2f0cf397/package.json#LL90C12-L90C12

**Comment by hecmas** [comment]
You can find all the info in the [snarkjs](https://github.com/iden3/snarkjs?tab=readme-ov-file#7-prepare-phase-2) repo.

**Comment by zkronos73** [comment]
Information requested it's inside snarkjs repo.
