### ISSUE TITLE
node main_executor.js error: heap out of memory

### ISSUE THREAD

**Issue by lightning-li** [0xPolygonHermez/zkevm-proverjs#192]
I executed the following command according to the instructions provided in the https://github.com/0xPolygonHermez/zkevm-techdocs/blob/main/mulmod-opcode/v.1.0/opcode-mulmod.pdf : `node --max-old-space-size=16384 src/main_executor.js /path/zkevm-testvectors/inputs-executor/calldata/op-mulmod_0.json -r /path/zkevm-rom/build/rom.json -d -s`. However, the command failed to run, and I encountered the following error message: `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`.

I'm wondering if this program requires a machine with more than 16GB of memory to run correctly. In the documentation, it just suggests using the `--max-old-space-size=4096` option.

Env:
- node version: v16.0.0
- os: macOS Apple M1 Pro

**Comment by zkronos73** [comment]
Depends of test, need more or less memory, it's a general recomendation. Thanks.

**Comment by zkronos73** [comment]
Depends of test, need more or less memory, it's a general recomendation. Thanks.
