### ISSUE TITLE
The sm_padding_kk_test.js fails

### ISSUE THREAD

**Issue by AndriianChestnykh** [0xPolygonHermez/zkevm-proverjs#205]
The `**test/sm/sm_padding_kk_test.js**` fails due to wrong polynoms it defines for in the keccakf.pil (both main & develop branches as of now)

```
Pil does not pass
keccakf.pil:15:  plookup not found w=1 values: 1:0,2043,2,2041
keccakf.pil:16:  plookup not found w=1 values: 1:0,2047,0,2047
keccakf.pil:17:  plookup not found w=1 values: 1:0,2047,0,2047
keccakf.pil:18:  plookup not found w=1 values: 1:0,2047,0,2047
```

I wonder if that can be easily fixed as I consider to re-using the Keccak proof in other solutions?

**Comment by zkronos73** [comment]
I reviewed, it's outdated test before change from 9 to 44 bits of keccak. To build constant table of plookup need a least 23 bits, (11 bits for all values of kA, and 11 bits for all values of kB, and one extra bit for kGateType. I try to fix test.

**Comment by zkronos73** [comment]
https://github.com/0xPolygonHermez/zkevm-proverjs/pull/207
