### ISSUE TITLE
How is the lastAccess flag forced to zero when addr does not change.

### ISSUE THREAD

**Issue by yczhangsjtu** [0xPolygonHermez/zkevm-proverjs#22]
https://github.com/0xPolygonHermez/zkevm-proverjs/blob/ecdcbe1dcd82b9f9fb2058e3c5cf03a4a0ca4ac2/pil/mem.pil#L16

It seems that the following three polynomials are the only ones enforcing the correctness of lastAccess.

```
    lastAccess * (lastAccess - 1) = 0;
    ISNOTLAST { lastAccess*(  addr' - addr - (step'-step) )  +   (step'-step) } in INCS;
    (1 - lastAccess) * (addr' - addr) = 0;
```

However, it seems that a malicious prover may always set lastAccess to be one, without breaking any of these polynomials. As a result, the second polynomial here only enforces that the addresses are sorted, while the step column is completely ignored.

**Comment by jbaylina** [comment]
Actually it's not forced. But if you set it to 1 then you must increase the address. (INC polynomial does not includes 0. It goes from 1 to 2**23)

At the end the accesses must match with the accesses in the main machine. So if you decide to increase the address before the last access then the permutation check in the main state machine will not match.

**Comment by yczhangsjtu** [comment]
I see. Thank you for the explanation.
